version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_taskdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'taskdb'
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: 'password'
    volumes:
      - taskdb_data:/var/lib/mysql
      - ./queries.sql:/docker-entrypoint-initdb.d/queries.sql
    restart: unless-stopped

volumes:
  taskdb_data:
    driver: local
